version: '3.5'

services:
  db:
    image: mariadb:10.3
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        WORDPRESS_SHA1: ${WORDPRESS_SHA1}
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      WORDPRESS_SITE_URL: ${WORDPRESS_URL}
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"

volumes:
  db-data:
  site-data:

networks:
  default:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 192.168.91.0/24
